# Site settings
title: "天码科技工作室"
email: iskycode.163.com
url: https://skycodetech.github.io
description: "天码科技工作室专注于软件产品开发，提供较多优秀产品，支持软件定制化服务，欢迎进行商务合作！"
skills: 'Web开发 - 移动开发 - 用户体验设计'
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: 天码科技工作室
  location: 地点
  social: 联系方式
  credits: 声明

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: qq
    url: tencent://message/?uin=575510804
  - title: weibo
    url: http://weibo.com/iskycode


# Postal address (add as many lines as necessary)
address:
  - line: 北京市 海淀区
  - line: 中关村

# Credits content
credits: '本工作室信誉良好，客户评价较高，欢迎与我们合作，包您满意！QQ：575510804'

# Build settings
markdown: kramdown
permalink: pretty
